#! /bin/sh

touch aclocal.m4
cvs commit -f -m "Timestamp" aclocal.m4

touch Makefile.in scintilla/Makefile.in \
	scintilla/src/Makefile.in include/Makefile.in ltdl/Makefile.in \
	src/Makefile.in tests/Makefile.in
cvs commit -f -m "Timestamp" Makefile.in scintilla/Makefile.in \
	scintilla/src/Makefile.in include/Makefile.in ltdl/Makefile.in \
	src/Makefile.in tests/Makefile.in

touch configure
cvs commit -f -m "Timestamp" configure
