#! /bin/bash

# usage:
#		sync-dist <version-number>
# example:
#		sync-dist 1.49
# puts files
#		fxscintilla-1.49.tar.gz
#   fxscintilla-1.49.zip
# on the FXScintilla project's download page.

cd snapshot
rsync --rsh=ssh -r $1 pini@savannah.nongnu.org:/upload/fxscintilla/FXScintilla.pkg