#! /bin/bash

# usage:
#		tarball devel|release [<scintilla_release> [<minor_release>]]
# example:
#		tarball release 1_40 3
# produces
#		snapshot/1.40.3/fxscintilla-1.40.3.tar.gz
# and
#		snapshot/1.40.3/fxscintilla-1.40.3.zip


if [ "$1" = "devel" ]; then
		devel=true
else
		devel=false
fi
	
major=$2
minor=$3

# Name
name="fxscintilla-"
if [ ! -z $major ]; then
		version=`echo $major | sed 's/_/./'`
		if [ ! -z $minor ]; then
				version="${version}.${minor}"
		fi
else
		version="cvs"
fi
name="${name}${version}"
# Tag
if [ ! -z $major ]; then
		tag="FXSCINTILLA-${major}"
		if [ ! -z $minor ]; then
				tag="${tag}_${minor}"
		fi
else
		tag="HEAD"
fi


if [ ! -d snapshot ]; then
	mkdir snapshot
fi
cd snapshot
if [ ! -d ${version} ]; then
	mkdir ${version}
fi

rm -fr fxscintilla
cvs -z3 -w export -r "${tag}" fxscintilla

if [ "$devel" = "false" ]; then
		cd fxscintilla
		rm -fr scintilla/gtk scintilla/win32
		cd ..
fi

mv fxscintilla $name

binaries='*.png *.ico *.cur *.jpg *.bmp'

tar cvzf ${version}/${name}.tar.gz $name
zip -lr ${version}/${name}.zip ${name} -x ${binaries}
zip -ur ${version}/${name}.zip ${name} -i ${binaries}

mv $name fxscintilla

ls -l ${version}
cd ..
