#! /bin/bash

# usage:
#		tarball devel|release [<scintilla_release> [<minor_release>]]
# example:
#		tarball release 1_40 3
# produces
#		snapshot/fxscintilla-1.40.3.tgz

if [ "$1" = "devel" ]; then
		devel=true
else
		devel=false
fi
	
major=$2
minor=$3

if [ ! -d snapshot ]; then
	mkdir snapshot
fi
cd snapshot

rm -fr fxscintilla

if [ ! -z $major ]; then
		tag="FXSCINTILLA-${major}"
		if [ ! -z $minor ]; then
				tag="${tag}_${minor}"
		fi
		cvs -w export -r "${tag}" fxscintilla
else
		cvs -w export -r HEAD fxscintilla
fi

find fxscintilla -type f ! \( \
		-name makefile -o \
		-name '*.png' -o \
		-name '*.ico' -o \
		-name '*.cur' -o \
		-name '*.jpg' -o \
		-name '*.bmp' \) \
	-exec unix2dos -o {} \;

cd fxscintilla

if [ "$devel" = "false" ]; then
		rm -fr scintilla/gtk scintilla/win32
		rm -f scintilla/scintilla.dsp
		rm -f scintilla/scintilla.dsw
		rm -f scintilla/fox/scintilla.dsp
		rm -f scintilla/fox/scintilla.dsw
fi

if [ ! -z $major ]; then
		name="../fxscintilla-"`echo $major | sed 's/_/./'`
		if [ ! -z $minor ]; then
				name="${name}.${minor}"
		fi
		name = "${name}.tgz"
else
		name="../fxscintilla.tgz"
fi
rm -f $name

if [ "$devel" = "false" ]; then
		tar cvzf $name scintilla
else
		tar cvzf $name .
fi

ls -l $name
cd ../..
